[project]
name = "agent-router"
version = "0.1.0"
description = "Dapr Agent Router Reaction"
readme = "README.md"
requires-python = ">=3.13,<3.14"
dependencies = [
    "dapr==1.18.1",
    "drasi-reaction-sdk",
    "fastapi==0.140.13",
    "fastmcp-slim[server]==3.4.4",
    "pydantic==2.13.4",
    "pydantic-handlebars==0.2.1",
]

[tool.uv.sources]
drasi-reaction-sdk = { path = "../../sdk/python", editable = true }  # Local package allows for more recent fastapi versions
