# generated by datamodel-codegen:
#   filename:  BootstrapStartedSignal.yaml
#   timestamp: 2026-06-03T03:04:26+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class BootstrapStartedSignal(ControlSignal):
    kind: Literal['bootstrapStarted']
