# generated by datamodel-codegen:
#   filename:  ChangeNotification.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from pydantic import Field
from typing_extensions import Annotated

from . import ChangePayload
from .Notification import Notification


class ChangeNotification(Notification):
    op: str
    payload: ChangePayload
    seq: Annotated[int, Field(description='The sequence number of the source change')]
