# generated by datamodel-codegen:
#   filename:  ChangePayload.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, RootModel

from . import ChangeSource


class RecordUnknown(RootModel[Optional[Dict[str, Any]]]):
    root: Optional[Dict[str, Any]] = None


class ChangePayload(BaseModel):
    source: ChangeSource
    before: Optional[RecordUnknown] = None
    after: Optional[RecordUnknown] = None
