# generated by datamodel-codegen:
#   filename:  ChangeSource.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from pydantic import BaseModel, Field
from typing_extensions import Annotated


class ChangeSource(BaseModel):
    queryId: Annotated[
        str, Field(description='The ID of the query that the change originated from')
    ]
    ts_ms: int
