# generated by datamodel-codegen:
#   filename:  ControlPayload.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import ChangeSource


class ControlPayload(BaseModel):
    source: ChangeSource
    kind: str
