# generated by datamodel-codegen:
#   filename:  ControlSignal.yaml
#   timestamp: 2026-06-03T03:04:26+00:00

from __future__ import annotations

from pydantic import BaseModel


class ControlSignal(BaseModel):
    kind: str
