# generated by datamodel-codegen:
#   filename:  ControlSignalNotification.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field
from typing_extensions import Annotated

from . import ControlPayload
from .Notification import Notification


class ControlSignalNotification(Notification):
    op: Literal['x']
    payload: ControlPayload
    seq: Annotated[int, Field(description='The sequence number of the control signal')]
