# generated by datamodel-codegen:
#   filename:  ControlEvent.yaml
#   timestamp: 2026-06-03T03:04:26+00:00

from __future__ import annotations

from typing import Literal

from . import ControlSignal
from .ResultEvent import ResultEvent


class ControlEvent(ResultEvent):
    kind: Literal['control']
    controlSignal: ControlSignal
