# generated by datamodel-codegen:
#   filename:  DeletedSignal.yaml
#   timestamp: 2026-06-03T03:04:26+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class DeletedSignal(ControlSignal):
    kind: Literal['deleted']
