# generated by datamodel-codegen:
#   filename:  Header.yaml
#   timestamp: 2026-06-03T03:04:25+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import HeaderItem


class Header(BaseModel):
    header: HeaderItem
