# generated by datamodel-codegen:
#   filename:  Op.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from enum import Enum


class Op(Enum):
    i = 'i'
    u = 'u'
    d = 'd'
    x = 'x'
    h = 'h'
    r = 'r'
