# generated by datamodel-codegen:
#   filename:  ReloadHeader.yaml
#   timestamp: 2026-06-03T03:04:27+00:00

from __future__ import annotations

from typing import Literal

from pydantic import Field
from typing_extensions import Annotated

from .Notification import Notification


class ReloadHeader(Notification):
    op: Literal['h']
    seq: Annotated[
        int, Field(description='The sequence number of last known source change')
    ]
