# generated by datamodel-codegen:
#   filename:  RunningSignal.yaml
#   timestamp: 2026-06-03T03:04:26+00:00

from __future__ import annotations

from typing import Literal

from .ControlSignal import ControlSignal


class RunningSignal(ControlSignal):
    kind: Literal['running']
