# generated by datamodel-codegen:
#   filename:  ViewItem.yaml
#   timestamp: 2026-06-03T03:04:25+00:00

from __future__ import annotations

from typing import Union

from pydantic import Field, RootModel
from typing_extensions import Annotated

from . import Data, Header


class ViewItem(RootModel[Union[Header, Data]]):
    root: Annotated[Union[Header, Data], Field(title='ViewItem')]
